### ISSUE TITLE
Implement --build-for in addition to --platform

### ISSUE THREAD

**Issue by cmatsuoka** [canonical/craft-application#254]
### What needs to get done

When `platforms:` is used, craft applications should be able to select build platforms using `--build-for`, according to the following rules:

- If there's only one platform entry with the specified target architecture, choose that one.
- If that results in more than one entry, and there's one entry using the architecture name as the platform name, choose that one.
- Otherwise fail with an error.

### Why it needs to get done

`--build-for` is extensively used and there's a reasonable way to map it to pick platform entries.

**Comment by sergiusens** [comment]
The second entry looks like it tries to solve for:

```
platforms:
    arm64:
    rpi4:
         build-for: arm64
```
