### ISSUE TITLE
Support CRAFT_VERBOSITY_LEVEL

### ISSUE THREAD

**Issue by tigarmo** [canonical/craft-application#264]
### What needs to get done

The purpose of this environment variable is to set the initial verbosity level of the application's emitter. Its possible values are the values of the EmitterMode (as strings), see [how Snapcraft uses it](https://github.com/canonical/snapcraft/blob/8.0.4/snapcraft/cli.py#L163)

### Why it needs to get done

For parity, as users expect to be able to use this environment variable to configure the verbosity.

**Comment by lengau** [comment]
Fixed in https://github.com/canonical/craft-application/pull/289
