### ISSUE TITLE
Remote build: Support attaching a build to a user-provided project

### ISSUE THREAD

**Issue by lengau** [canonical/craft-application#274]
### What needs to get done

The remote build service should be able to take a user-provided project name and use that for the remote build. Checks to make include:

1. That the user is allowed to create git repositories on this project
2. That the user is allowed to create recipes on this project
3. Whether this project is public or private (the build service should also expose this in a public API)

### Why it needs to get done

This is how we'll support private remote-build. The application will be able to accept a project name and build on a private project.

**Comment by mr-cal** [comment]
Fixed via https://github.com/canonical/craft-application/pull/293
