### ISSUE TITLE
remote build: improve UX when credentials don't exist

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#337]
### What needs to get done

Craft-application should log a message that launchpad credentials don't exist on the machine (and include the expected location).

### Why it needs to get done

Particularly in non-interactive workflows (like CI jobs), the remote-builder will hang for 900 seconds waiting for authentication and not provide the user with any meaningful output of why it couldn't log in to launchpad.

**Comment by mr-cal** [comment]
Closing because we've decided not to support using `remote-build` in CI.  CI builds for snaps should be orchestrated via snapcraft.io.

**Comment by lengau** [comment]
What happens in an ssh session? If we get interactive, but non-desktop, sessions where this occurs we should fix those.

**Comment by mr-cal** [comment]
Seems like a reasonable scenario but I'll defer to @sergiusens to decide.
