### ISSUE TITLE
`ServiceFactory` should have `update_kwargs`

### ISSUE THREAD

**Issue by mattculler** [canonical/craft-application#378]
### What needs to get done

Add a `ServiceFactory.update_kwargs` method, analogous to `update` on `dict`.

### Why it needs to get done

Typically the way the current `set_kwargs` method is used, overriding callers will need to copy the set of default kwargs before appending the new kwargs they care about.  With `update_kwargs`, only the new kwargs will need to be specified by callers.  Adding `update_kwargs` will allow applications to couple more loosely to `craft-application`, and reduce the amount of code the applications contain.

**Comment by lengau** [comment]
Let's go even further and deprecate `set_kwargs` so we can yank it at the next major release
