### ISSUE TITLE
Error message "Multiple builds match the current platform" could be more helpful

### ISSUE THREAD

**Issue by thp-canonical** [canonical/craft-application#382]
### What needs to get done

The current error is defined here:

https://github.com/canonical/craft-application/blob/7eba6693af5466381659788053791281b1cf2235/craft_application/errors.py#L140-L147

It gets raised here:

https://github.com/canonical/craft-application/blob/7eba6693af5466381659788053791281b1cf2235/craft_application/services/lifecycle.py#L413-L419

If the error would get the `build_plan: list[models.BuildInfo]` as parameter, and with `models.BuildInfo` having a `platform` attribute:

https://github.com/canonical/craft-application/blob/7eba6693af5466381659788053791281b1cf2235/craft_application/models/project.py#L75-L89

This would allow the error message to read something like this instead, making it easier for the user to reason about what the craft tool *thinks* are the platforms that match:

> Multiple builds match the current platform: ["platform1", "platform2"]

Not sure if this is platform-specific, or if we should print more for each matching `models.BuildInfo` in the `build_plan`, or if we e.g. should just print out the `build_plan` as-is.

### Why it needs to get done

This will make it easier for users of craft applications to figure out which builds do match, and pick one of them when using `--platform` or `--build-for` in the next invocation of the tool, without having to dig into other files.

**Comment by tigarmo** [comment]
Sounds good, thanks for the suggestion!
