### ISSUE TITLE
Spec a multi-base strategy

### ISSUE THREAD

**Issue by cmatsuoka** [canonical/craft-application#453]
### What needs to get done

Evaluate current proposals for multi-base handling in platforms and grammar and write a specification outlining the solution.

### Why it needs to get done

Craft tools need a strategy to handle multi-base projects with the ability to do grammar based on archs or bases.

**Comment by cmatsuoka** [comment]
Also check PF-3887

**Comment by mr-cal** [comment]
Spec'd in ST124, prototyped in CRAFT-3668.  The craft-grammar work will be prototyped in CRAFT-3669.
