### ISSUE TITLE
Import and add profile support for the `init` command

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#508]
### What needs to get done

* Import the `init` command from its private location
* Add support for `--profile`
    * Profiles should be registered like craft-parts plugins

### Why it needs to get done

To allow snapcraft to create a profile for testing with `snapcraft init --profile test`.

Design notes: https://docs.google.com/document/d/1lK0tb1eAapbuRoWipJsJ5HdQ27XZk9CJLWqdE52SjPU/edit#heading=h.qrrrlg3fcxw

**Comment by dariuszd21** [comment]
Relates to: https://github.com/canonical/craft-application/issues/452

**Comment by mr-cal** [comment]
Oop, thanks.  I missed that existing ticket.
