### ISSUE TITLE
Support build plans

### ISSUE THREAD

**Issue by tigarmo** [canonical/craft-application#60]
### What needs to get done

Every existing application has some version of support for multiple builds based on a "build matrix". This matrix needs craft-application support because it ends up informing the entire rest of the process. For example:

- The build base might depend of the current build configuration;
- The instances created by craft-providers need the current build configuration (specially in their names);
- The parts lifecycle need the current build config to inform the target/build-for variables and such.

### Why it needs to get done

For feature-parity with the existing applications.

**Comment by tigarmo** [comment]
Currently snapcraft has a workflow that is like this (in pseudocode):

```
build_plan = get_build_plan(yaml, parsed_args)
for build_info in build_plan:
    if <provider mode>:
        run_in_provider(build_info)
    else:
        project = get_project(yaml, build_info)
        <run lifecycle/pack>
```

[source](https://github.com/snapcore/snapcraft/blob/main/snapcraft/parts/lifecycle.py#L196)

**Comment by sergiusens** [comment]
Created #67
